[normal]
quit = ["q"]
refresh = ["r"]
up = ["k", "Up"]
down = ["j", "Down"]
top = ["g", "Home"]
bottom = ["G", "End"]
command_mode = [":"]
help = ["?"]
keymap = ["K"]
aliases = ["A"]
show = ["Enter"]
diff = ["d"]
status = ["s"]
operation_log = ["o"]
bookmark_list = ["L"]
resolve_list = ["v"]
file_list = ["f"]
tag_list = ["t"]
root = ["w"]
repeat_last = ["."]
toggle_patch = ["p"]
fetch = ["F"]
push = ["P"]
rebase_main = ["M"]
rebase_trunk = ["T"]
new = ["n"]
next = ["]"]
prev = ["["]
edit = ["e"]
commit = ["c"]
describe = ["D"]
bookmark_set = ["b"]
abandon = ["a"]
rebase = ["B"]
squash = ["S"]
split = ["X"]
restore = ["O"]
revert = ["R"]
undo = ["u"]
redo = ["U"]

[command]
submit = ["Enter"]
cancel = ["Esc"]
backspace = ["Backspace"]
history_prev = ["Up"]
history_next = ["Down"]

[confirm]
accept = ["y"]
reject = ["n", "Esc"]
