[normal]
quit = ["q"]
refresh = ["r"]
up = ["k", "Up"]
down = ["j", "Down"]
top = ["g", "Home"]
bottom = ["G", "End"]
command_mode = [":"]
show = ["Enter"]
diff = ["d"]
toggle_patch = ["p"]
fetch = ["F"]
push = ["P"]
rebase_main = ["M"]
rebase_trunk = ["T"]
new = ["n"]
commit = ["c"]
describe = ["D"]
bookmark_set = ["b"]
abandon = ["a"]
rebase = ["B"]
squash = ["S"]
split = ["X"]
restore = ["O"]
revert = ["R"]
undo = ["u"]
redo = ["U"]

[command]
submit = ["Enter"]
cancel = ["Esc"]
backspace = ["Backspace"]

[confirm]
accept = ["y"]
reject = ["n", "Esc"]
